### PR TITLE
Handle image orientation with pillow

### PR DESCRIPTION
**Pull request by derVedro**
There are nasty dependencies like PyGObject, cairo, GExiv2 in this project, but they are unnecessary. Pillow can deal with exif tags, so why not use it for that?

### CODE REVIEW

**Comment by davidfischer-ch** [comment]
Indeed. Great work.

**Comment by jrast** [comment]
I there a release planed including this PR? Would be nice as installation is easier without those dependenicies.

**Comment by derVedro** [comment]
I hope so. I did some more stuff in the summer that could really help the project. But I didn't have the time to finish it properly. I would prefer to merge my possible future PRs into a new version.

**Comment by davidfischer-ch** [comment]
Hello @derVedro, @jrast,

Let me know when you both think its time to release it.

Have a nice week.

**Comment by davidfischer-ch** [comment]
Done :)

**Pull request merged**
